### PR TITLE
adding  hardy.md

### PR DESCRIPTION
**Pull request by zihaoxu20010109**
This is Hardy

### CODE REVIEW

**Review by christopherbarnett — CHANGES_REQUESTED** [review]
Thanks Hardy! Can you please add some basic info and project ideas when you get the chance?

**Review by rowantran — COMMENTED** [review]
can you add a section about yourself and then a section about the project ideas? see here for an example: https://github.com/ucsb-cs148-f21/project-t10-animelist/pull/2/files

just want to make sure you dont lose any points since the lab asks to include those details

**Review by rowantran — APPROVED** [review]
LGTM!

**Review by jvoucsb — APPROVED** [review]

**Comment by jvoucsb** [comment]
closing it seems to be already added

please wait until there are two approvals and then merge in instead of pushing directly onto the branch.

**Pull request closed without merging**
